apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${APP_NAMESPACE}
  labels:
    deployment: ${APP_NAME}
  annotations:
    prometheus.io/should_be_probed: "true"
spec:
  progressDeadlineSeconds: 180
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true" # requires istio 1.2
    spec:
      imagePullSecrets:
        - name: az-ca-registry
      containers:
        - image: "sbcloudauthenticator.azurecr.io/${APP_NAME}"
          name: ${APP_NAME}
          env:
            - name: AZURE_ACCOUNT_NAME
              value: ${AZURE_ACCOUNT_NAME}
            - name: AZURE_STORAGE_KEY
              value: ${AZURE_STORAGE_KEY}
            - name: AZURE_WALLETS_SHARE
              value: ${AZURE_WALLETS_SHARE}
            - name: LOG_LEVEL
              value: INFO
          ports:
            - containerPort: 8080

          # define a liveness probe
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          # define a readiness probe
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
---

apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  namespace: ${APP_NAMESPACE}
  labels:
    service: ${APP_NAME}
  annotations:
    prometheus.io/should_be_scraped: "true"
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 8100
      targetPort: 8100
      protocol: TCP
      name: metrics
    - port: 8200
      targetPort: 8200
      protocol: TCP
      name: healthcheck
  selector:
    app: ${APP_NAME}
